Datapath_RISCV/source/riscv_pkg.sv
Datapath_RISCV/source/adder.sv
Datapath_RISCV/source/alu.sv
Datapath_RISCV/source/branch_unit.sv
Datapath_RISCV/source/datapath.sv
Datapath_RISCV/source/imm_gen.sv
Datapath_RISCV/source/mux_2_1.sv
Datapath_RISCV/source/mux_4_1.sv
Datapath_RISCV/source/next_pc_logic.sv
Datapath_RISCV/source/pc_reg.sv
Datapath_RISCV/source/reg_file.sv
Control_RISCV/source/alu_decoder.sv
Control_RISCV/source/control_unit.sv
Control_RISCV/source/main_decoder.sv
Core_RISCV/source/riscv_core.sv
Memorias_Bus/rtl/data_ram.sv
Memorias_Bus/rtl/memory_mmio_system.sv
Memorias_Bus/rtl/mmio_interconnect.sv
Memorias_Bus/rtl/program_rom.sv
Entradas_Jugador1/rtl/debounce_button.sv
Entradas_Jugador1/rtl/j1_inputs_peripheral.sv
UART/rtl/baud_rate_generator.sv
UART/rtl/uart_mmio_fifo.sv
UART/rtl/uart_mmio_peripheral.sv
UART/rtl/uart_receiver.sv
UART/rtl/uart_transmitter.sv
Salidas_Locales/rtl/buzzer_controller.sv
Salidas_Locales/rtl/peripherals_mmio.sv
Salidas_Locales/rtl/seven_seg_decoder.sv
Salidas_Locales/rtl/seven_seg_display.sv
Salidas_Locales/rtl/status_led.sv
Nucleo_VGA/modulos_nucleo_vga/vga_top.sv
Nucleo_VGA/modulos_nucleo_vga/video_ram.sv
Nucleo_VGA/modulos_nucleo_vga/vga_timing.sv
Nucleo_VGA/modulos_nucleo_vga/pixel_to_tile.sv
Nucleo_VGA/modulos_nucleo_vga/tile_address.sv
Nucleo_VGA/modulos_nucleo_vga/tile_decoder.sv
Nucleo_VGA/modulos_nucleo_vga/rgb_output.sv
Integracion/rtl/batalla_naval_top.sv
